
name: Andrew Herriot's portfolio
description: A portfolio of work experience and projects by Andrew Herriot
author: Andrew Herriot

baseurl:
url: www.aherriot.com
port: 3000

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/
  volunteer:
    output: true
    permalink: /volunteer/:path/

exclude:
- README.md
- Gemfile
- Gemfile.lock
